version: "2"
output:
  sort-order:
    - linter
    - file
linters:
  default: all
  disable:
    - exhaustruct
    - gochecknoglobals
    - gocognit
    - mnd
    - nestif
    - nilnil
    - paralleltest
    - varnamelen
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
    govet:
      enable-all: true
    perfsprint:
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
