name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ stable, oldstable ]
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install GolangCI-Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.5
      - run: make lint
      - run: make test_coverage
      - name: Upload code coverage to codecov
        if: matrix.go == 'stable'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
