name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ stable, oldstable ]
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go mod tidy
      - run: make lint
      - run: make test_coverage
      - name: Upload code coverage to codecov
        if: matrix.go == 'stable'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
